[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python enrich_tracks.py"
